import type { GetServerSideProps } from "next";
import Head from "next/head";
import BodySingle from "dh-marvel/components/layouts/body/single/body-single";
import { getComic, getComics } from "dh-marvel/services/marvel/marvel.service";
import CardHero from "dh-marvel/components/card/card-hero";
import { Comic } from "types/getComic";
import Grid2 from "@mui/material/Unstable_Grid2/Grid2";

export default function Index({ data }: { data: Comic[] }) {
  getComic(2).then((data) => console.log(data));
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <BodySingle title={"Sample"}>
        <Grid2
          sx={{ padding: "2rem" }}
          container
          spacing={3}
          justifyContent="center"
        >
          {data?.map((comic) => (
            <Grid2 xs={12} sm={6} md={4}>
              <CardHero {...comic} />
            </Grid2>
          ))}
        </Grid2>
      </BodySingle>
    </>
  );
}

export const getServerSideProps: GetServerSideProps = async () => {
  const { data: comics } = await getComics(100, 100);

  const data = comics.results
    .filter((comic) => !!comic.thumbnail && !!comic.description)
    .slice(0, 12);

  return {
    props: {
      data: data,
    },
  };
};
