import type { GetServerSideProps } from "next";
import Head from "next/head";
import BodySingle from "dh-marvel/components/layouts/body/single/body-single";
import { getComics } from "dh-marvel/services/marvel/marvel.service";
import CardHero from "dh-marvel/components/card/card-hero";
import { GetComic } from "types/getComic";

export default function Index({ data }: GetComic) {
  console.log(data);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <BodySingle title={"Sample"}>
        {data?.results?.map((comic) => {
          return <CardHero {...comic} />;
        })}
      </BodySingle>
    </>
  );
}

export const getServerSideProps: GetServerSideProps = async () => {
  const { data } = await getComics(12, 12);

  return {
    props: {
      data,
    },
  };
};
